jkuhlmann/cgltf

cgltf.h

Hi, I took some time and implemented support for these features. As of now the code does not run properly, because it segfaults somewhere in line 1565
` out_data->accessors[i].stride = out_data->accessors[i].buffer_view->stride; `. Not sure what is going on there. Strangely, when I remove the sampler parsing
```
else if (name_length == 8
&& strncmp((const char*)json_chunk + tok->start, "samplers", 8) == 0)
{
i = cgltf_parse_json_samplers(options, tokens, i + 1, json_chunk, out_data);
}
```
it works. I did not modify the "Fix up pointers" code. Maybe you have an idea why.
**Edit: I found the bug, everything works now. Cheers.**
___
A couple of notes:
- Images only support URIs at the moment, no support for `bufferView` and `mimeType`
- Renamed `baseColorFactor` to base_color, because it …

Materials, Textures, Images, Samplers

---

cgltf.h

This commit fixes all MSVC warnings at /W3 when compiling cgltf:
- cgltf_size was defined as unsigned long which is 32-bit on MSVC even
when pointers are 64-bit, which triggers pointer truncation warnings
when integers are stored in cgltf_texture pointer; it seems more
appropriate to use size_t anyway
- cgltf_sampler was storing 4 integer values using cgltf_float which was
triggering int->float cast warnings; these should probably use some
cgltf enum but for now use cgltf_int
- jsmn was inconsistent in use of size_t vs unsigned int in the
interface, fix jsmn_parse num_tokens parameter to match other jsmn
functions

Fix MSVC conversion warnings

---

cgltf.h

GLTF spec says that component type declares the type of a scalar
component, and type - vec2/etc. - declares the component count.
All vector-like component types were unused and potentially confusing to
the user. In fact, when I tried to use cgltf first, I expected position to be rgb32f because that enum type was prominently available :)

Remove component types that are not present in GLTF spec

---

cgltf.h

Quick summary of interface tradeoffs:
- ~~Main scene is called "main_scene"; it's called "scene" in GLTF but I felt that this name is too easy to mistype as "scenes". Happy to change to "scene" if that seems better.~~ This was changed to `scene` to match GLTF spec naming.
- ~~Each node has TRS separate from matrix (unioned to save space), and has_matrix to disambiguate. While we could compute matrix from TRS and decompose matrix into TRS, leaving that to application seemed best. I considered using an enum for has_matrix but decided otherwise for simplicity. Happy to change that to an enum if that seems better.~~ This was changed to individual booleans for each of T/R/S/matrix, and non-unioned arrays for clarity.
- TRS components and matrix are represented using plain C arrays. I see that …

Implement support for scenes and nodes

---

README.md
cgltf.h

We now parse perspective and orthographic camera definitions from GLTF
file as well as node->camera bindings.
Camera is structured as an enum type + union of two possible struct
values, with straightforward future extensions if GLTF adds more camera
types.

Implement camera support

---

cgltf.h

This PR introduces several changes that clean up the code for future improvements:
- Instead of a mixture of cgltf_json_strcmp and strncmp we now always use cgltf_json_strcmp. Additionally, we don't need to perform case-insensitive comparison - GLTF spec is case sensitive as far as I understand.
- Many places need to copy a JSON string to heap; there's now a function for that
- Several places need to parse a JSON float array; there's now a function for that
- All internal functions now consistently use the same function signature style, where the last parameter is the pointer to the structure they're parsing
Also the PR fixes potential but unlikely OOB access in boolean parsing.

Refactoring

---

README.md
cgltf.h
test/main.c

This change switches to a model where cgltf_parse variants allocate
cgltf_data instead of filling user-provided struct. This clarifies the
interface - cgltf_parse will return a valid data object only when it
returns success status, in which case cgltf_free must be used to
deallocate memory.
If a parse error happens in the middle of parsing the document, we're
going to call cgltf_free and return a failure status. This mechanism
isn't 100% robust since some pointers aren't always initialized - this
will be fixed separately.
The code was slightly restructured to delay the creation of cgltf_data
object up until many errors have already been detected, and also this
change has a few memory leak fixes.
The outer loop was also changed to the more usual "iterate through all
keys" style that is …

Change cgltf_parse and cgltf_parse_file to return a pointer to data

---

README.md
cgltf.h
fuzz/gltf.dict

We now can parse materials that use specular/glossiness workflow. GLTF
extension spec says that information about metallic-roughness and
specular-glossiness can coexist; while this is unlikely to happen in
practice, this is why instead of an enum that picks the material
representation we have two booleans.
Also add tokens for fuzzing and update README.

Implement support for KHR_materials_pbrSpecularGlossiness

---

cgltf.h
test/main.c

We now parse "asset" object which contains the generator (that can be
useful to figure out what pecularities of the data we should expect),
copyright and version information.
cgltf_data::version was misleading - it referred to GLB version only and
had nothing to do with GLTF version, so it was removed. However we now
check that the version matches GLB spec.
Also rename Gltf constants to Glb - again, they define the container
format, not the GLTF data encoded inside it.

Implement support for asset information parsing

---

README.md
cgltf.h

Since accessors can refer to values up to 16 scalars, the maximum size
of min/max arrays is 16.
We do not always know the size of the arrays because "type" is in the
same object and may happen after the arrays, so we just parse the entire
array - up to 16 elements to not cause heap overflow.

Parse accessor min/max limits

---

cgltf.h

This is very simple - just need to set the unlit flag. Not updating README for now to avoid merge conflicts with upcoming PRs for two final extensions I'd like to have support for.

Implement support for KHR_materials_unlit

---

cgltf.h

This change adds support for parsing light information into lights array
and parsing node->light reference. We parse directional, point and spot
information; spot data is saved into two float variables since it felt
excessive to create a separate struct for this.
Additionally there were a few missing checks in the extension parsing
for other extensions, which this change adds.

Implement support for KHR_lights_punctual

---

cgltf.h

This is probably a regression from the pointer fixup rework:
- scene pointer wasn't correctly set up during parsing, so if scene
index was 0, we'd leave the pointer as 0.
- material pointer in the primitive wasn't fixed up at all.

Fix pointer fixup bugs

---

cgltf.h

This change reworks string and array parsing to avoid memory leaks on malformed documents.
Previously, if a JSON element specifying string/array data occurred in the document twice, the second occurrence would completely erase the previously parsed data, causing a memory leak.
With this change, we rely on new helpers parse_json_string and parse_json_array to handle this case by returning a parse error. Additionally, we use the same helpers to return a memory error (the need to differentiate between these is why the functions return int), which is then propagated to the user.
Additionally, this change fixes a couple of cases where memory_alloc failures weren't handled. We should now be completely leak-proof and handle all memory allocation failures.

Make sure cgltf deallocates all memory and handles all memory allocation failures

---

cgltf.h

Parent pointers are set up during pointer fixup. Take this opportunity to differentiate between required pointers and optional pointers - for example, children pointers that we need to access to set up parents are required but previously could be parsed as NULL.
This change also verifies that a node has at most one parent and root nodes don't have parents; this effectively guarantees that the portions of the node graph that are reachable from scene roots are acyclic. This was trivial to do so I added this to main parse function instead of an extra validation function.

Add parent pointer to nodes

---

README.md
cgltf.h

Previously, the user had to explicitly handle several different possible
ways for buffer data to be provided:
- In GLB files, first buffer is declared inside the file and can be read
via cgltf_data::bin
- In GLTF files with external URIs, files need to be opened to read
buffers
- In GLTF files with data URIs, Base64 decoding has to be performed on
URI data.
We now have a function, cgltf_load_buffers, that handles all of these
differences and automatically loads buffer data from any source. Only
Base64 octet-stream data URIs are handled for simplicity.
The allocated buffer data is deallocated using cgltf_free.

Implement cgltf_load_buffers

---

cgltf.h

This change parses the full name of the attribute and stores it for
future reference; the enum type of the attribute is still present for
known attributes and is called type.
Closes #21. (this is not quite what I was hoping for, but let's do this for now and we can improve this later if need be)

Implement support for custom attributes

---

cgltf.h

These are helpful for applications that don't care about the specific
TRS composition of node transforms and just want the raw matrix data.
While we could go the other way as well and provide TRS, that requires
decomposing the matrix which is not as numerically stable, and would
introduce interfaces that could become invalid if GLTF adds skew as an
extension.

Add helper functions to extract node transforms

---

cgltf.h
test/main.c

With this CI tests will run almost all of the code on glTF sample models
- this will validate that the code that loads external buffers and
parses Base64 data URIs is correct.
One of the sample models used a data URI with application/glb-buffer mime type, so this change makes Base64 decoding more generic.
Also while I'm here fix the buffer assignment for GLB-stored buffers (contributes to #14).

Test cgltf_parse_file and cgltf_load_buffers in CI

---

cgltf.h

When first buffer is loaded from the GLB binary chunk, if the chunk is
too small we'd be returning a data pointer to the user while supplying a
buffer that's too short to access safely, so this has to be an error.
Additionally fix handling of buffers with no URI - URI is optional as
per spec, and presumably buffers without a URI may have their contents
supplied via extensions. It seems better to keep the buffers like that
as is, that way the application can load these manually separately.

Fix GLB buffer handling when GLB buffer is too short

---

cgltf.h
fuzz/main.c
test/main.c

This series of changes introduces cgltf_validate that performs the most critical validation checks (that are most likely to cause the application to misbehave when using parsed data), most of these are validating different sizes of different arrays against each other.
None of these checks require buffer access; if we introduce them later, we might need to add validation flags to the options.
Contributes to #14. (I feel like this set of validation checks is sufficient to address that with the exception of index data validation that I will submit separately)

Add optional validation support

---

cgltf.h

Right now the terms of MIT license prohibit copying cgltf.h into another
project without including the LICENSE file. This change embeds the
boilerplate into the .h file which makes it legal (IANAL) to just
distribute *one* file.

Embed license boilerplate into cgltf.h

---

cgltf.h

If a client explicitly sets `file_type_gltf` in the passed-in options, then they would see an error result when attempting to parse a JSON-based glTF.

Fix logic in file_type check.

---

cgltf.h

This fixes "extraneous closing brace" errors that would occur when attempting to include the same
file twice, caused by the extern C scope. This is also more consistent with the Sean Barrett libs.

Fix include guard.

---

README.md
cgltf.h
test/CMakeLists.txt
test/test_all.py
test/test_conversion.cpp

Fixes #46.
For the integer-based reading function, note that we return cgltf_size values instead of cgltf_int values.  For the rare cases where clients need to read negative values, they should use the float-based reader instead.
The reason we use size_t is that it's what we need internally for sparse support. Most clients will be reading indices anyway when using the integer-based reader function.

Add data conversion functions.

---

cgltf_write.h
test/CMakeLists.txt
test/test_all.py
test/test_write.cpp

This writes out nicely-formatted JSON and ignores externally-referenced
buffer data.
Does not yet support sparse accessors, skinning, or morph targets, but
it's a good start and I've been using it successfully for a couple weeks
using several test models.
Fixes #52

Introduce cgltf_write.h

---

cgltf.h

Fixes this warning:
cgltf.h(1804): warning C4456: declaration of 'j' hides previous local declaration
cgltf.h(1768): note: see declaration of 'j'

Fix variable shadowing

---

cgltf_write.h

It doesn't look like cgltf_write needs the CGLTF_IMPLEMENTATION to function, and with these headers cgltf_write compiles standalone

Add missing includes to cgltf_write.h

---

cgltf_write.h

Some locales use , instead of . as a decimal separator which causes cgltf_write to generate invalid JSON
Locales are a pain to deal with and pulling in a float-to-string library adds quite a lot of code, so this is a reasonable solution IMO

Convert decimal commas to decimal points when writing floats

---

cgltf.h

Fix -Wunused-parameter warnings by explicitly marking unused arguments
as such, and -Wmissing-field-initializers by specifying all 3 struct
fields for jsmn_parser.

Fix gcc/clang warnings for -Wall/-Wextra

---

cgltf.h

cgltf_size <-> cgltf_float conversions require explicit casts.

Fix MSVC cast warnings in x64 builds

---

cgltf_write.h

This is perferable to crashing and is consistent with cgltf_parse_file.

Return error when unable to open file for writing.

---

cgltf.h

This is particularly useful for clients who need to check the required list for things like Draco, so they can error out gracefully if they do not support it.

Expose extensionsUsed and extensionsRequired.

---

cgltf.h

This substantially improves parsing performance on large glTF files,
eliminating backtracking during parse and making parsing linear (at
least in practice) in the input size.
All tests from glTF-Sample-Models still pass; this doesn't seem to affect
fuzz safety one way or the other.
Fixes #66.

Enable JSMN_PARENT_LINKS

---

cgltf.h

extensions_used/extensions_required were not being freed on exit (found
using fuzzing).
Additionally, duplicate definitions of extensionsUsed could result in further
memory leaks because of incorrect error handling during string array parse.
Also move json_data after extensions_used since this isn't part of the
actual semantical data in glTF file and is just an utility like
bin_data.

Fix memory leaks with extension lists

---

cgltf.h
fuzz/data/TriangleWithoutIndices.gltf
fuzz/main.c

This change makes cgltf memory-safe, at least as far as fuzzing is concerned :)
After this change I ran fuzzing for about 100 CPU-hours without any issues.
I'm not willing to prove the safety but it's definitely way better than it used to be.
There's one big problem that this change is fixing, which is that jsmn can generate non-sensical
JSON token structures. At some point it would be nice to fix the problem at its core, but for now we do the following:
1. Enable JSMN strict mode. This rejects *some* instances of malformed JSON documents, but not all of them.
2. Fix a few missing error checks in `cgltf_parse_json_texture_view` extension parsing.
3. Add an UNDEFINED token after the token stream. This makes sure that when the token stream is invalid, we will hit an UNDEFINED token which …

 Make parser memory-safe 🎉

---

cgltf.h

When you have a `base` which doesn't contain a path separator, e.g. "scene.gltf", then `cgltf_combine_paths` returns the base file rather than the URI. This means `cgltf_load_buffers` will open the original GLTF file rather than the .bin containing the buffer data, leading to invalid data and possibly a crash.
Returning `uri` rather than `base` for this case fixes it.

Wrong result from `cgltf_combine_paths` when `base` has no path separator

---

cgltf_write.h

The 'auto' keyword for inferred types is a C++ feature.

Fix cgltf_write C99 build errors - remove 'auto'

---

cgltf_write.h

On Mac OS v10.14.5, the following example won't compile when you run `gcc test.c`:
```
// test.c
#define CGLTF_WRITE_IMPLEMENTATION
#include "cgltf_write.h"
int main(void) {
cgltf_options options = {0};
cgltf_data data = {
.asset = {
.generator = "test",
.version = "2.0"
},
};
cgltf_write_file(&options, "test.gltf", &data);
return 0;
}
```
Here are a subset of the corresponding error messages:
```
In file included from test.c:2:
./cgltf_write.h:205:92: error: unknown type name 'bool'
static void cgltf_write_boolprop_optional(cgltf_write_context* context, const char* label, bool val, bool def)
^
./cgltf_write.h:205:102: error: unknown type name 'bool'
static void cgltf_write_boolprop_optional(cgltf_write_context* context, const char* label, bool val, bool def)
^
./cgltf_write.h:234:8: …
```

Add #include<stdbool.h> to cgltf_write.h

---

cgltf.h

This commit addresses issue https://github.com/jkuhlmann/cgltf/issues/74

Avoid warning when compiling as C99

---

cgltf.h

This change fixes a few issues with the existing implementation:
- Normalized 8-bit unsigned integers were decoded using CHAR_MAX as the
divider; signedness of char is not specified by the standard and it's
*very* common to have char be signed (it's usually unsigned on ARM
systems and signed everywhere else), so this used 127 instead of 255
- In general it's incorrect to rely on USHRT/UCHAR/etc. limits - we are
dealing with fixed-width quantities, and in theory the short/char/etc.
could have different sizes or limits. It's more correct to hardcode the
numbers from the spec.
- glTF spec doesn't define normalization behavior for 32-bit integers.
Note that it also doesn't define a signed 32-bit integer type and it's
unlikely that one will happen without the other. This is relevant
because …

Fix a few corner cases in cgltf_component_read_*

---

cgltf.h

While technically cgtlf preserves morph target names (if present) via
cgltf_mesh::extras, because this is a string array packed inside an
object it's very inconvenient to parse it out outside of cgltf code.
Morph target names are not technically part of the schema, but the
specification explicitly mentions targetNames as the common way to
convey this information:
> Implementation note: A significant number of authoring and client
> implementations associate names with morph targets. While the glTF 2.0
> specification currently does not provide a way to specify names, most
> tools use an array of strings, mesh.extras.targetNames, for this
> purpose. The targetNames array and all primitive targets arrays must
> have the same length.

Implement targetNames parsing

---

cgltf.h

index variable in the loop was shadowing index argument; fix this by
using memset.

Fix -Wshadow warning

---

cgltf.h
cgltf_write.h

There are some minor, but annoying issues when compiling cgltf with `gcc` **8.3.1**:
- The source code uses unnamed unions (for perspective and orthographic cameras), which is not legal C99, and `gcc` gives the warning (with `-pedantic`):
```
cgltf.h:423:3: warning: ISO C99 doesn’t support unnamed structs/unions [-Wpedantic]
```
- There are implicit signed/unsigned conversions that trigger warnings when compiling with `-Wextra`:
```
cgltf.h: In function ‘cgltf_json_to_int’:
cgltf.h:1730:65: warning: operand of ?: changes signedness from ‘int’ to ‘long unsigned int’ due to unsignedness of other operand [-Wsign-compare]
int size = (cgltf_size)(tok->end - tok->start) < sizeof(tmp) ? tok->end - tok->start : sizeof(tmp) - 1;
^~~~~~~~~~~~~~~~~~~~~
cgltf.h: In function ‘cgltf_json_to_float’: …
```

C99 conformance fix

---

cgltf.h

buffer->data can be NULL because the user hasn't loaded the buffers or
the buffers don't have URI/BIN contents. In this case our current
behavior is to crash when reading the data; this change makes it so that
the accessor functions fail instead.
Fixes #89.

Verify buffer->data in all accessor helper functions

---

cgltf_write.h

It should be written as mimeType, not mime_type.

Correct MIME type property name of images

---

cgltf_write.h

Explicitly cast from cgltf_size to int to avoid unnecessary warnings. Also replaces a case of int for size_t and a couple of cases of size_t for cgltf_size.

Shed 64-bit warnings for cgltf_write

---

cgltf_write.h

The property name for a light's color is currently `light` but it should be `color`.

Correct light color property name

---

cgltf.h

The `FILE*` operations are still used by default, but it's now configurable via `cgltf_options` how the (file) data is read and freed.
This is supposed to fix #94 .

Changed file operations to use callbacks.

---

cgltf.h

Two unused variables and one unreachable line.

Fix MSVC /W4 warnings

---

cgltf.h
cgltf_write.h

When `__INTELLISENSE__` is defined, `cgltf.h` turns on `CGLTF_IMPLEMENTATION`
to enable code completion, etc. in MSVC. This change does the same for
JetBrain's CLion.

Add intellisense support in CLion

---

cgltf.h
cgltf_write.h

This change adds support to read and write glTF files that use
the `KHR_draco_mesh_compression` extension. The extension can be
specified per primitive, which is why cgltf_primitive now has 2
new fields: `has_draco_mesh_compression` and `draco_mesh_compression`.
`draco_mesh_compression` contains a buffer view and a list of
attributes.
It is important to note that the extension may or may not be
required. A primitive can specify both compressed and uncompressed
data. While this doesn't affect the parsing, it does affect the
writing since the proper extensionsUsed/Required needs to be
specified. To achieve this, this change adds support for required
extensions in `cgltf_write.h` (see `required_extensions_flag` in
`cgltf_context`). The extension is deemed required when a primitive
has no …

Add support for KHR_draco_mesh_compression

---

cgltf.h
cgltf_write.h

This extension has entered the ratification process. The current
draft can be found at https://github.com/KhronosGroup/glTF/pull/1756/.
It is very likely that the extension will be accepted as is.

Add support for KHR_materials_clearcoat

---

README.md
cgltf.h

This adds "extensions" dictionary to objects, exposing extension name and start + end offsets. Simpler way would have been doing same way as extra.field, but I felt this to be better, as glTF 2.0 extensions-field has to be "[dictionary object](https://github.com/KhronosGroup/glTF/blob/master/specification/2.0/README.md#reference-extension)".
This could also be helpful for providing utility parsers for [vendor specific](https://github.com/jkuhlmann/cgltf/issues/103)/wip extensions in separate files.
Notes: 
1. I only implemented the reading part, didn't have plan to implement this for cgltf_write.h currently.
2. ~~"Draft pull request" as fuzzer still found some memory leaks but failures are only detected after 3+ hours.~~ edit: multithreaded fuzzing after 3h no longer gives leaks
Pseudo …

Easier access to vendor/unsupported extensions

---

cgltf.h

The extension code used to crash if some allocations failed, this change fixes that.

Fix error handling for memory allocations

---

README.md
cgltf.h
cgltf_write.h

Khronos has finalized the spec and is close to ratifying it. Filament
will be a reference implementation so we require cgltf support.
More information at:
https://github.com/KhronosGroup/glTF/pull/1698
ThreeJS support is arriving here:
https://github.com/mrdoob/three.js/pull/19690
@romainguy

Add support for KHR_materials_transmission.

---

README.md
cgltf.h
cgltf_write.h

The `KHR_materials_ior` extension is simple and exposes only one new parameter to control the index of refraction of a surface.
This change has been tested by `test_write` using a Khronos [sample model](https://github.com/KhronosGroup/glTF-Sample-Models/pull/268).

Add support for KHR_materials_ior

---

README.md
cgltf.h
cgltf_write.h

The `KHR_materials_specular` extension is fairly simple and exposes three new parameters:
- `specularFactor`, float, default = `1.0f`
- `specularColorFactor`, float3, default = `{1.0f, 1.0f, 1.0f}`
- `specularTexture`, a 4-channel texture that combines `specularFactor` and `specularColorFactor`
This change has been tested by `test_write` using a [Khronos sample model](https://github.com/KhronosGroup/glTF-Sample-Models/pull/268).

Add support for KHR_materials_specular

---

README.md
cgltf.h

Specification:
https://github.com/KhronosGroup/glTF/tree/master/extensions/2.0/Vendor/EXT_meshopt_compression
This change implements parsing support for EXT_meshopt_compression; it
only parses the extension data and allows the caller to run the
decompression itself.
To make integration easier, this change adds a data pointer to buffer
view; accessor helpers use the buffer view data as an override to
buffer's data - this allows us to implement any other buffer view based
compressors if they get created without changing accessor reading more.
To decode the data, one must use a spec-compliant decoder; here's an
example of using meshoptimizer library in concert with cgltf to decode
buffer views (after which one can continue using cgltf accessor helpers
without any changes):
```c++
static …
```

Implement support for EXT_meshopt_compression

---

cgltf.h

targetNames isn't normative and as such can technically be something
other than an array. tinygltf seems to use targetNames:null in some
cases to designate an empty target array; cgltf previously would refuse
to parse files like this and now it discards non-array targetNames
values instead.

Fix parsing of files with targetNames:null

---

cgltf.h
cgltf_write.h

KHR_materials_specular definition was tweaked this week; specularTexture is now broken apart into two textures, specularColorTexture (RGB) and specularTexture (A). 
This change in the draft specification follows the convention used by many of glTF's other extensions, where colors and factors are specified as separate textures in the extension (e.g. sheenColorTexture and sheenRoughnessTexture).  This allows for flexibility in how the texture data is packed.  This new arrangement also allows for specularColorTexture and specularTexture to have a unique texture_transforms if necessary.
/CC @emackey

KHR_materials_specular now uses two textures, specularTexture and specularColorTexture

---

README.md
cgltf.h
cgltf_write.h

KHR_materials_variants adds two arrays: a top-level array of asset
variants, where each variant can have a name and arbitrary extra info,
and a per-primitive mappings array that establishes a map between
variants and materials.
Specification:
https://github.com/KhronosGroup/glTF/blob/master/extensions/2.0/Khronos/KHR_materials_variants/README.md
Since modeling arrays-of-arrays is awkward wrt memory management, this
change represents mappings as a flat array of material-variant pairs.
When parsing we unpack the source data into that representation.
variant is stored as an index; while we could store a pointer as well,
for runtime representation it seems best to preserve the indexing
scheme. We could change this in the future if need be...
In addition to adding support for this extension, …

Add support for KHR_materials_variants

---

cgltf.h
fuzz/main.c

This is mostly a followup for #132 since I forgot a few error checks there, but I've also ran the fuzzer for a few hours and found one more problem in Draco mesh compression parsing (also on invalid files).

Fix a few parsing crashes on invalid inputs

---

README.md
cgltf.h
cgltf_write.h

This extension enables reading and writing of refractive volumes, as defined by the draft extension, KHR_materials_volume.
See: https://github.com/KhronosGroup/glTF/pull/1726

Added support for KHR_materials_volume.

---

cgltf.h

This fixes the -Wpedantic warning which is triggering a build failure.
For some reason this isn't visible in PR statuses, and only shows up upon merge :( I think we saw odd issues with Travis before on this repository but it wasn't clear why they happened...

Fix ANSI C build

---

cgltf.h
cgltf_write.h

The perspective camera's `aspectRatio` and `zfar` are [both optional](https://github.com/KhronosGroup/glTF/blob/f16e9846d741f0acaa46918c8d71cf6093a0f14a/specification/2.0/schema/camera.perspective.schema.json#L38). Previously, if you ran `test_write` on
```json
{
"asset": {
"version": "2.0"
},
"cameras": [
{
"type": "perspective",
"perspective": {
"yfov": 0.5,
"znear": 0.01
}
}
]
}
```
it would treat the aspect ratio and zfar both as zero
```json
{
"asset": {
"version": "2.0"
},
"cameras": [
{
"type": "perspective",
"perspective": {
"aspectRatio": 0,
"yfov": 0.5,
"zfar": 0,
"znear": 0.00999999978
}
}
]
}
```
With this change, `test_write` will produce
```json
{
"asset": {
"version": "2.0"
},
"cameras": [
{
"type": "perspective",
"perspective": {
"yfov": 0.5,
"znear": 0.00999999978
}
}
]
} …
```

Add perspective camera aspect ratio and zfar property flags

---

README.md
cgltf.h

- `cgltf_write` *does* support extras.
- Add some notes about decoding image URIs.

Minor updates to documentation.

---

cgltf.h
cgltf_write.h

Adds support for https://github.com/KhronosGroup/glTF/tree/master/extensions/2.0/Khronos/KHR_texture_basisu
In the glTF file, this extension is defined on the texture object, so it seems logical that we define this cgltf extension data on the `cgltf_texture` object. This PR adds a new flag, `has_basisu` and a new `cgltf_image` property, `basisu_image` to `cgltf_texture`.  This solution allows loaders that do not support KTX2 and basisu textures to continue loading any fallback texture that may be defined on the model.
I considered making a small change, where we can `#define SUPPORT_BASISU`, remove this new `cgltf_texture::basisu_image`, and instead just load the basisu image directly into `cgltf_texture::image`.  Open to suggestions here, but both seem functionally equivalent.
If you'd …

Add KHR_texture_basisu parsing

---

cgltf.h

fix: when loading a gltf with "KHR_lights_punctual" extension with lights with no intensity (default 1), the gltf was saved with intensity 0 (instead of 1 or actually nothing because it's the default)
add all lights values by default

fix: Add default values for"KHR_lights_punctual" 

---

cgltf.h

cgltf_light does not have `extras`, though lights may contain `extras `([light.schema.json](https://github.com/KhronosGroup/glTF/blob/master/extensions/2.0/Khronos/KHR_lights_punctual/schema/light.schema.json)). With Blender when adding extras to point light data they get exported into the light object.
This change adds `cgltf_extras` to `cgltf_light` and parses them from light object.

Add cgltf_extras to cgltf_light

---

cgltf.h
cgltf_write.h

all `byte` prefixed properties are parsed and written allowing cgltf_size rather than int boundaries.
partial fix for !151

fix parsing/writing of cgltf_size byte props (!151)

---

cgltf_write.h

In newer gcc versions (tested on gcc 11.1.0) compiling with `-O2 -Wall -Werror` flags produces warnings like
```
In file included from /cgltf/test/test_write.cpp:3:
In function ‘void cgltf_write_node(cgltf_write_context*, const cgltf_node*)’,
inlined from ‘cgltf_size cgltf_write(const cgltf_options*, char*, cgltf_size, const cgltf_data*)’ at /cgltf/test/../cgltf_write.h:1183:20:
/cgltf/test/../cgltf_write.h:112:41: error: null destination pointer [-Werror=format-truncation=]
112 |                 context->tmp = snprintf ( context->cursor, context->remaining, __VA_ARGS__ ); \
|                                ~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/cgltf/test/../cgltf_write.h:138:25: note: in expansion of macro ‘CGLTF_SPRINTF’
138 | …
```

Fix format-truncation warning for gcc

---

README.md
cgltf.h
cgltf_write.h

[KHR_materials_emissive_strength](https://github.com/KhronosGroup/glTF/blob/931632a785ac377f854213e764ed618c6a1b4f7f/extensions/2.0/Khronos/KHR_materials_emissive_strength/README.md) is a new extension that recently entered the "Release Candidate" status. This one is pretty simple in that the core specification limits the emissiveFactor to values in the range of [0.0 - 1.0]. This extension provides an additional multiplier to amplify emission beyond 1.0.
After discussion (below) this implementation defines a new flag, `has_emissive_strength` and an `emissive_strength` struct that embodies this float property.  The original approach is quoted here to preserve the history of this PR conversation, but no longer applies ... 
> Rather than following the route of other extensions with a …

Add support for KHR_materials_emissive_strength.

---

cgltf.h
cgltf_write.h

PR: https://github.com/KhronosGroup/glTF/pull/2027
Note: the extension hasn't been merged to glTF yet but all the spec
corrections wrt schema have been made so the schema shouldn't change at
this point.

Implement support for KHR_materials_iridescence

---

cgltf.h
cgltf_write.h

No comma after *_max_enum since one is not supposed to add anything after it. Test suite runs through without errors. Hope I did not miss anything.
Custom attributes have names starting with an underscore, no semantic index parsing for these (applications will probably have their own way to deal with them).

Added *_max_enum suffixes to enumerated types and custom attributes handling

---

cgltf.h

Fix unpack_floats() for signed integers.
The return type of `cgltf_component_read_index` is unsigned, which does not work if the underlying type is signed.

Fix unpack_floats() for signed integers.

---

cgltf.h

There is no cgltf_accessor_num_components() and I guess it's too late to rename it.

Fix documentation of cgltf_num_components()

---

cgltf.h

With this change, we now disregard the 'type' field when parsing the camera type, and instead solely rely on the orthographic/perspective keys, and also enforce a single consistent section type during the process.
This ensures that cgltf_camera::data has been filled just once with data that came from a single JSON blob; without this it's possible to fill one struct and then fill another struct which may overwrite some union fields with invalid data, which is a significant issue for extras which contains offsets into the JSON blob.
The reason why we don't need to parse 'type' at all is that the specification says that when type is perspective or orthographic, files without a corresponding JSON section are invalid.
Note that we aren't as strict as we could possibly be, since we don't …

Ensure that camera has a single consistent type in the file

---

cgltf.h
cgltf_write.h

This change moves texture view resource reclamation to a separate function to make it easier to change, add (currently unused) options parameter to extras parsing, and removes pbr_material_roughness extras support for consistency - no other material sub-component supports extras right now.
This extracts the more mechanical parts of #184 to make that one easier to merge.

Refactor code a little in preparation for extras rework

---

cgltf.h
cgltf_write.h

This change switches cgltf_extras to embed the JSON data the same way we handle unprocessed extensions, by copying it to heap. While this results in a few extra (ha!) heap allocations, in practice the other data such as object names et al dominates the allocation traffic. The benefit here is that it makes using the library simpler - extras can be read from directly without copying, and this means that the original glTF data can be discarded which can improve memory consumption.
The downside, of course, is that there's quite a few places where extras is used. This can be mitigated by #118 in the future, but for now we diligently free extras for every struct that has them, something that is made easier by the fact that most structs that contain extras also contain extensions.
Note that this …

Copy extras data into cgltf_extras::data during parsing

---

cgltf_write.h

Also write `texture_info->scale` as field `strength` for occlusion texture.

distinct normal/occlusion texture info when writing

---

cgltf.h

Hi. As mentioned in #183, `cgltf_buffer_view_data()` is useful for parsing embedded image data. I wasn't sure if the dependency on `<stdint.h>` is something that should be avoided, but I assumed not since it's included in the implementation.

Export cgltf_buffer_view_data

---

test/test_conversion.cpp

Both Draco and Meshopt compression requires extra code to unpack accessor data; we also now use a more principled analysis of the extensions referenced instead of simply relying on the file name.
This should fix CI errors due to a more recent set of files from glTF-Sample-Models that now include Meshopt-compressed models.

Update test_conversion to skip compressed inputs

---

cgltf.h
cgltf_write.h

bufferView is not a valid attribute; it looks like the code was probably copied from Draco where this attribute is valid. See schema: https://github.com/KhronosGroup/glTF/blob/main/extensions/2.0/Vendor/EXT_mesh_gpu_instancing/schema/glTF.EXT_mesh_gpu_instancing.schema.json
Also we were missing skip_json for both this extension and Draco; this can be necessary to skip extras data.
Without this change, cgltf can't load SimpleInstancing.gltf from glTF-Sample-Models (recently added)

Fix support for EXT_mesh_gpu_instancing

---

cgltf.h

This can be useful to recover the index from the pointer for cases when another cgltf data structure contains the pointer.
For animation samplers/channels, the channel references the sampler, but nothing references the channel; it felt inconsistent to only add the sampler function, even though the channel function is unlikely to be useful.
Fixes #202.
Closes #206, closes #207, closes #208, closes #209, closes #210, closes #211, closes #212, closes #213

Implement getter functions for indices of various objects

---

cgltf.h

This is mostly focused on cgltf_accessor_unpack_floats, but also adds a counterpart cgltf_accessor_unpack_indices.
The optimizations reduce the overhead by extracting some common code out of the per-element loop, and also implementing a fast path for direct memcpy. Without the fast path, this results in ~10% faster glTF parsing (tested end-to-end on Amazon Bistro exterior scene); with the fast-path, this makes the parsing 1.5x faster. Note that the time includes loading gltf/buffer data from files, parsing/validation and some minor data reorganization, so the gains may be more significant in other applications - the numbers above are from gltfpack.

Optimize data extraction from accessors

---

cgltf.h

this shall resolve issue 220.
[https://stackoverflow.com/questions/15127522/how-to-ifdef-by-compilertype-gcc-or-vc](https://stackoverflow.com/questions/15127522/how-to-ifdef-by-compilertype-gcc-or-vc)
Fixes #220

replace "#ifdef _WIN32" with "#ifdef _MSC_VER"

---

cgltf.h

This is the only place in cgltf.h where 0 is used as a pointer constant.

Use NULL instead of 0 to silence -Wzero-as-null-pointer-constant

---

cgltf.h
cgltf_write.h

This change removes support for extras and extensions from cgltf_accessor_sparse and cgltf_texture_view to simplify memory management.
The motivation for this change is that both accessor_sparse and texture_view are deeply nested in glTF structures and simultaneously rarely extended; there are no known extensions for internals of sparse accessors, and only one (KHR_texture_transform) extension for texture views which is supported by cgltf natively.
The presence of these inflates the cgltf data structures; while it would be reasonable to do given specific use cases, we do not have specific use cases here.
Additionally, for cgltf_texture_view, this type is heavily used by the materials which is a very active area of development in glTF ecosystem. Many newer extensions are added gradually …

Simplify extensions/extra handling by trimming their support

---

cgltf.h

Instead of blindly casting int to enum, we handle the values defined in the JSON spec in a switch case.
This may seem redundant, but this fixes a UBSAN error on invalid glTF files, and it's literally the only enum where we rely on the enum values matching glTF values (everything else is either string based in glTF, or using integers that aren't small and sequential so we convert it with a switch). So this is more consistent and a little safer; this also ensures that the values actually conform to the max_enum member.

Explicitly parse primitive type enum

---

cgltf.h

This change attempts to flag more invalid glTF files as invalid when this likely interferes with the mesh processing by causing crashes.
- Fix parsing of cgltf_size by using cgltf_json_to_size in a couple places where int was used erroneously and replacing negative numbers with 0. We would previously return -1 when the JSON token was invalid and an arbitrary negative value if a negative number was present, but this runs a high risk of an integer overflow during any of the size computation, which causes a security risk. In the future it would be nicer to use a limit for positive values as well (for example, glTF spec says that all sizes should be limited to 2^53), as with this change there is still a risk of overflow during multiplication.
- Fix validation of accessors - an invalid …

Improve mesh accessor validation

---

cgltf.h

Some names in glTF data structures are required and some are optional.
We normally ensure that names that are required can't be NULL as a byproduct of how they are parsed: required names usually come up when they are JSON object keys, so a lack of a name means the object isn't parsed.
Material variants are an odd exception: the name is required (in fact it's the only thing that a variant has...), but it's stored as a "name" key in an array of objects because the extension needs to maintain variant order. It's natural for the user to assume that the name is not NULL as the spec requires that, but it can be NULL in non-compliant documents, so we validate this now.

Validate that material variant names aren't NULL

---

cgltf.h

glTF specification guarantees that the indices of builtin attributes are natural numbers; atoi can return a negative number, which is likely to cause problems for client code (for example, even if it attempts to range-check the texture coordinate index before writing it to internal mesh representation, index < 8 will not work because index can be negative).

Ensure that for builtin types, attribute index is non-negative

---

cgltf.h
cgltf_write.h

Opinions on whether VLA's are a good feature tend to be pretty mixed. Regardless of opinion, Microsoft's MSVC compiler does not support them, and any project attempting to use the C89 standard won't either.
The VLA's in this library aren't even of variable size - their sizes are known at compile time.
Love the library, thanks for building & supporting it!

Remove VLA usage for GLB size constants

---

cgltf.h

Validation of input lengths must be performed by comparing the length with the remainder of the input data; the latter can be safely computed because we validate the remainder after every step incrementally.
Before this change, length validation was doing math in 32-bit space and could thus overflow, exposing data after the input buffer to the parser.
This was always a problem on 32-bit systems; it only became a problem on 64-bit systems after the VLA change, as before it GlbHeaderSize et al had type cgltf_size.
Found by fuzzing. Regression (on 64-bit systems) since #238.

Fix integer overflow during GLB chunk length validation

---

cgltf_write.h

Adds a translation from `cgltf_primitive_type` to gltf primitive rendering mode in the writer.
This PR is a fix for the issue https://github.com/jkuhlmann/cgltf/issues/243.
The bug was introduced when `cgltf_primitive_type` was added in commit afe4d3aa29f47f45c21e563f500e49f4e10d6428 and resulted in rendering mode was offset by one in the written file.
Thanks for a great library!

Fix primitive rendering mode in cgltf_write

---

cgltf.h
cgltf_write.h

This extension is structurally similar to KHR_materials_ior in that it's just a float, no textures or any other parameters.
Specification:
https://github.com/KhronosGroup/gltf/tree/main/extensions/2.0/Khronos/KHR_materials_dispersion
Tested end-to-end in gltfpack (https://github.com/zeux/meshoptimizer/pull/660) plus tested via test_write_glb by taking the example from https://github.com/KhronosGroup/glTF/pull/2340#issuecomment-1850997118, using test_write_glb to convert it to a new .glb file and loading the resulting file in Babylon.JS sandbox.

Implement support for KHR_materials_dispersion

---

cgltf.h

cgltf_validate will now check that EXT_mesh_gpu_instancing nodes adhere to basic contracts:
- The mesh must be present on the node; if absent, an implementation is likely to accidentally dereference a NULL pointer
- Attributes must have consistent counts; this is critical because the number of instances is implicitly specified via accessor counts and if any of them diverge, an out of bounds access is likely to occur

Improve EXT_mesh_gpu_instancing validation

---

README.md
cgltf.h
cgltf_write.h

Specification:
https://github.com/KhronosGroup/glTF/tree/main/extensions/2.0/Vendor/EXT_texture_webp

Implement support for EXT_texture_webp

---

cgltf.h

When using cgltf something that comes up often is the need to find the accessor corresponding to a given attribute for a primitive (e.g. positions or second UV channel). The code for this is simple, but it is needed frequently and it would be nice to include a helper for this in cgltf proper.

Add cgltf_find_accessor helper

---

cgltf.h

`cgltf_sampler` defines filter and wrap modes using `cgltf_int`, which requires referencing the glTF specification to interpret those integers. 
To fix this, enumerations representing valid glTF sampler filter and wrap modes are introduced. For backward compatibility, these enumerations retain their original integer values to allow implicit conversion to `cgltf_int`.
Project tests were run using `tests/test_all.py` on Windows (MSVC 19.41.34123) and Ubuntu (GCC 13.2) which passed without any errors. 
- `cgltf_filter_type` includes `cgltf_filter_type_undefined = 0` because the glTF specification indicates, "Client implementations SHOULD follow specified filtering modes. When the latter are undefined, client implementations MAY set their own default texture filtering settings." This will …

Add glTF sampler filters and wrap modes enums

---

cgltf.h

This PR introduces 3 improvements to the
`cgltf_accessor_unpack_indices` function:
1. Query `cgltf_num_components` and use it to load int vectors properly - this is useful for loading vec4 uint8_t joint indices.
2. Add support for uint8_t in slow path (for loop) in cases where data wasn't tightly packed (previously the function wouldn't do anything).
3. Return 0 on failure instead of failing silently and leaving memory uninitialized.

Change `cgltf_accessor_unpack_indices` to work with int vectors

---

cgltf.h

Previously we have supported sparse accessors for cgltf_accessor_unpack_floats but not for various read_ functions. This could lead to applications using read_ functions for specific cases and the code would work for most glTF files but fail on files with sparse data.
This change supports sparse indices by using binary search to find the index; the keys in sparse accessors are guaranteed to monotonically increase. This is still slower than a single linear pass that unpack_floats does, but will work correctly and have acceptable performance.

Support sparse accessors for cgltf_accessor_read_*

---

cgltf_write.h

cgltf_write.h has the incorrect name for `anisotropyStrength`.
The reader has the correct name.  See:
https://github.com/jkuhlmann/cgltf/blob/08470a2b08980cd3221002a9b2ef29a37e3111dc/cgltf.h#L4389
I noticed during round-trip testing that the name was getting changed, so this is a small fix to correct it.

Fix output name of anisotropyStrength

---

cgltf.h
test/CMakeLists.txt

This is necessary for POSIX systems to be able to implement file loading via mmap/munmap since munmap takes the size (unlike Windows). Without this, the implementation would need to keep a map from file pointer to file size to be able to unmap the file.
This change requires minor adjustment for people who use file callbacks but the change should be very straightforward and will be flagged during the upgrade by the compiler.

Add file size to cgltf_file_options::release callback
