jkuhlmann/cgltf

cgltf.h

After this change the code is both valid C99 and valid C++; this helps
to consume this library from C++ since you no longer have to have a .c
file to compile it - can just include it into an existing .cpp file.
Additionally this probably makes the library useful in earlier VS versions.

Fix compilation in C++ mode

---

cgltf.h

This change backfills all missing items for the elements from the spec
that we support.
Specifically:
- Textures and images now have names; they may contain important
semantic information or can be used for debugging.
- Accessors now have normalized attribute; without this it's impossible
to decode fixed point data correctly.
- Materials now have alpha mode and cutoff to be able to setup blending
correctly.
- Occlusion texture has "strength" instead of "scale"; we parse it into
"scale" field for simplicity.

Miscellaneous fixes to catch up with the spec

---

cgltf.h

- Change primitive type enum to have primitive_type prefix to
disambiguate it from cgltf_type enum
- Remove cgltf_rgba - one of the cases when it's used actually requires
an RGB type, it seems simpler and cleaner to use an array
- Rename pbr to pbr_metallic_roughness - this is required to be able to
support pbrSpecularGlossiness workflow later
- Rename base_color to base_color_factor, emission_color to
emission_factor, to match the spec

Change interface to match spec better

---

cgltf.h

We now parse morph targets for each mesh, morph weights for meshes,
morph weights for nodes and animation target "weights".
Morph targets use the same attribute structure as the primitive itself;
this results in a pretty deep object hierarchy :( This may be simplified
to a flat C array with accessor pointers later?

Implement support for morph targets

---

cgltf.h

This time we can run millions of iterations of llvm-fuzz without
crashing. There still are some cases where we may not parse the JSON
correctly due to lack of validation (e.g. when we expect an integer and
get a string instead, we will convert the integer to -1 and parse will
not fail). Also we're slowly leaking memory during the fuzzing process,
that's going to be fixed separately.
The key part of this change is checking keys for objects. When JSON
doesn't have correct structure for object contents, you can look at the
key and verify that its size is 1 - if it's not (it's usually 0), that's
an indication that there was no value that was paired with the key.
Because of this we introduce a macro to check the type and size of all
keys, and rigorously apply it to all object parsing loops. …

Substantially improve parser safety for malformed inputs

---

cgltf.h

This adds straightforward parsing of the texture transform (that has to
be done for each texture view) via the extension. has_transform can be
used to check if the transform is present.
This change also moves scale initialization into parse_texture_view. If
the texture isn't present, it shouldn't matter what the scale is.

Implement KHR_texture_transform extension

---

cgltf.h

With this change instead of hardcoding the index of the attribute into
the type enum, we separate it out into an integer. This means that we
now support an arbitrary number of UV sets; additionally if any exporter
exports more than 4 bone indices using JOINTS_1/WEIGHTS_1 then that
should work as well.

Implement generic support for parsing attribute index along with type

---

cgltf.h

We now validate primitive indices and sparse accessor indices for index
content - if the associated buffer is loaded, we compute the max index
and verify it's in bounds.
Additionally we now verify the component type of index accessors.
Fixes #14.

Implement index data validation

---

cgltf.h

Added missing default values that are supposed to be different from 0.

---

cgltf_write.h

Also implements the KHR_lights_punctual extension, but no other extensions and not "extras" data.
@prideout Do you mind taking a look?

Implemented writing all the missing core glTF data

---

README.md
cgltf.h

Added extras support.

---

cgltf.h
test/CMakeLists.txt
test/test_all.py
test/test_math.cpp

Scale for the X axis should be in the first row of the matrix, not the first column. Note that the existing math was very consistent with gl-matrix, aside from the handling of scale:
http://glmatrix.net/docs/mat4.js.html#line1079
For more background, including a test model exhibiting the issue, see:
https://github.com/google/filament/issues/1519

Fix transforms for non-uniform scale.

---

cgltf.h
test/test_conversion.cpp

Add cgltf_accessor_unpack_floats and smoke test.

---

cgltf.h

When parsing glTF 1.0 files, it helps to differentiate the error code so
that the user can be presented with an error message urging them to
convert the file.
GLB 1.0 files are easy to detect - they have the version number 1.
glTF 1.0 files are harder to detect. Technically they have asset.version
attribute equal to 1.0, but we parse the file in order and usually the
JSON blob has other collections, such as "accessors", before "asset".
What happens then is that we try to parse the array of accessors et al,
but in glTF 1.0 collections were objects (with key associated with
object name).
We could pre-scan the entire file looking for "asset", but this is
linear in token count, and as such moderately expensive. This change
conservatively assumes that if we are looking for an array and get the …

Add a separate error code for legacy (1.0) glTF files

---

cgltf.h

This change adds several more validation criteria:
- We were not successfully detecting node cycles before - a node could
not have more than one parent, but a cycle was possible. This creates
issues for code that traverses children or parents recursively. We now
use the standard cycle detection method on parent chain.
- We were not checking that scene roots don't have a parent. This is
usually more or less benign but it's the only other parent/child
validity check that could make sense...
- Previously, animation accessors were not validated wrt their element
count. This is somewhat tricky especially for morph targets - it's not
really feasible to parse animation data without knowing the morph target
count! - so we now carefully compute the expected number of values in
the output stream …

Improve validation to catch more cases of structurally unsound files

---

cgltf.h

Depends on `CGLTF_MALLOC`, `CGLTF_FREE`, `CGLTF_ATOI`, or `CGLTF_ATOF` not being defined.
Fixes #98.

Changed include of stdlib.h to be conditional.

---

cgltf.h

This fixes memory leaks in buffer loading (we used a on-heap temporary
buffer for paths but never freed it) and in Draco data (which was not
freed in cgltf_free).

Fix memory leaks

---

cgltf.h

Image and buffer paths are encoded as URIs in the glTF file. This means
that special characters, such as spaces, are percent-encoded.
This change adds a helper function, cgltf_decode_uri, that can decode a
URI in place; it also uses it when loading the buffers so that we pass a
path to file read callback instead of a path-URI combo.

Implement cgltf_decode_uri

---

cgltf_write.h

https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#gltfextras

Write gltf root extras

---

cgltf.h
cgltf_write.h

Specification:
https://github.com/KhronosGroup/glTF/tree/master/extensions/2.0/Khronos/KHR_materials_sheen
Warning, since the glTF-Sample-Models repository doesn't yet have a test for sheen, this is effectively not tested in CI; I've tried this on https://github.com/BabylonJS/MeshesLibrary/tree/master/Sheen and it seemed to work though.

Add support for KHR_materials_sheen

---

cgltf.h

Add optional asserts to cgltf_validate.

---

cgltf.h

Implement support for >2GB files on Windows

---

cgltf.h

Fix file data being released using the wrong function.

---

cgltf.h

In previous code if some memory tool did a 
#define free(A) free_dbg(A, stuff...)
it would conflict and not compile.
Sadly some memory checker tools integration requires it
For instance visual studio _CRTDBG_MAP_ALLOC (https://docs.microsoft.com/en-us/visualstudio/debugger/finding-memory-leaks-using-the-crt-library?view=vs-2022)

Allows preprocessor overwrite of free/alloc

---

cgltf.h

Fix memory leak in EXT_mesh_gpu_instancing code

---

cgltf_write.h

cgltf_light extras are not ignored on writing anymore
